# Generated by Django 4.2.20 on 2025-10-20 22:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_proficiency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('skills_to_target', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('include_epistemology_intro', models.BooleanField(default=False)),
                ('ai_first_demonstrates', models.BooleanField(default=False)),
                ('upload_primary_sources', models.BooleanField(default=False)),
                ('chatbot_finds_sources', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=255)),
                ('include_custom_historical_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('json_payload', models.JSONField()),
                ('readable_format', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_assignments', to='chat.assignmentrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_of_classes', models.ManyToManyField(blank=True, related_name='users', to='chat.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('used_in_rag', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_info', to='chat.assignmentrequirement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_info', to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInteractionSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.generatedassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.student')),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_sources', to='chat.assignmentrequirement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_primary_sources', to='chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.studentinteractionsession')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='classes', to='chat.generatedassignment'),
        ),
        migrations.AddField(
            model_name='class',
            name='list_of_students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='chat.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='chat.teacher'),
        ),
        migrations.AddField(
            model_name='assignmentrequirement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='chat.teacher'),
        ),
    ]
