# Generated by Django 4.2.20 on 2025-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrequirement',
            name='student_proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('expert', 'Expert')], default='beginner'),
        ),
    ]
