# Generated by Django 4.2.20 on 2025-11-13 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_assignmentrequirement_student_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedassignment',
            name='json_payload',
        ),
        migrations.RemoveField(
            model_name='generatedassignment',
            name='readable_format',
        ),
        migrations.AddField(
            model_name='generatedassignment',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
