# Generated by Django 4.2.20 on 2025-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_generatedassignment_json_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedassignment',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
