# Generated by Django 4.2.20 on 2025-12-15 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_generatedassignment_sources'),
    ]

    operations = [
    ]
