# Generated by Django 4.2.20 on 2025-12-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrequirement',
            name='guiding_question',
            field=models.TextField(default='How did muckrakers use evidence to expose specific social problems, and what did they hope to change as a result?'),
            preserve_default=False,
        ),
    ]
